# Generated by Django 5.1.4 on 2026-10-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_seed_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ("name",)},
        ),
    ]
