# Generated by Django 5.1.4 on 2026-10-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_intra_id"),
        ("accounts", "0004_alter_role_options"),
    ]

    operations = []
