# Generated by Django 5.1.4 on 2026-10-08 09:51

from django.db import migrations


def backfill_student_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Role = apps.get_model("accounts", "Role")
    UserRole = apps.get_model("accounts", "UserRole")
    database = schema_editor.connection.alias
    student = Role.objects.using(database).get(name="student")
    # Preserve existing permissions and skip anonymized accounts (schema §2.4).
    for user_id in (
        User.objects.using(database)
        .exclude(status="deleted")
        .values_list("id", flat=True)
        .iterator()
    ):
        UserRole.objects.using(database).get_or_create(user_id=user_id, role_id=student.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge_0002_user_intra_id_0004_alter_role_options"),
    ]

    # Reversal must not remove a student's baseline permission.
    operations = [migrations.RunPython(backfill_student_role, migrations.RunPython.noop)]
