# Generated by Django 5.1.4 on 2026-10-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "project",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TutorEligibilityRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eligibility_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tutor_eligibility_request",
            },
        ),
        migrations.CreateModel(
            name="TutorEligibilityRequestProject",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="evaluations.project"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.tutoreligibilityrequest",
                    ),
                ),
            ],
            options={
                "db_table": "tutor_eligibility_request_projects",
            },
        ),
        migrations.AddField(
            model_name="tutoreligibilityrequest",
            name="projects",
            field=models.ManyToManyField(
                related_name="eligibility_requests",
                through="evaluations.TutorEligibilityRequestProject",
                to="evaluations.project",
            ),
        ),
        migrations.CreateModel(
            name="EvaluationRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("awaiting_confirmation", "Awaiting confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "Passed"), ("failed", "Failed")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("feedback", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "picked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="picked_evaluation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_requests",
                        to="evaluations.project",
                    ),
                ),
            ],
            options={
                "db_table": "evaluation_request",
                "indexes": [
                    models.Index(
                        fields=["status", "project", "created_at"], name="eval_req_open_queue"
                    ),
                    models.Index(fields=["student", "status"], name="eval_req_student"),
                    models.Index(
                        fields=["picked_by", "status", "starts_at"], name="eval_req_picked_by"
                    ),
                    models.Index(fields=["status", "starts_at"], name="eval_req_expiry"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ends_at__isnull", True),
                                ("picked_by__isnull", True),
                                ("starts_at__isnull", True),
                            ),
                            models.Q(
                                ("ends_at__isnull", False),
                                ("picked_by__isnull", False),
                                ("starts_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="eval_req_pick_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("picked_by__isnull", False),
                                ("status__in", ["awaiting_confirmation", "confirmed"]),
                            ),
                            models.Q(
                                models.Q(
                                    ("status__in", ["awaiting_confirmation", "confirmed"]),
                                    _negated=True,
                                ),
                                ("picked_by__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="eval_req_pick_matches_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("starts_at__isnull", True),
                            ("ends_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="eval_req_slot_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("cancelled_at__isnull", False), ("status", "cancelled")),
                            models.Q(
                                models.Q(("status", "cancelled"), _negated=True),
                                ("cancelled_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="eval_req_cancel_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("expired_at__isnull", False), ("status", "expired")),
                            models.Q(
                                models.Q(("status", "expired"), _negated=True),
                                ("expired_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="eval_req_expire_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "confirmed"),
                            models.Q(("completed_at__isnull", True), ("result__isnull", True)),
                            _connector="OR",
                        ),
                        name="eval_req_result_only_confirmed",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TutorEligibility",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibilities",
                        to="evaluations.project",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_by_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_eligibilities",
                        to="evaluations.tutoreligibilityrequest",
                    ),
                ),
            ],
            options={
                "db_table": "tutor_eligibility",
                "constraints": [
                    models.UniqueConstraint(fields=("tutor", "project"), name="uniq_tutor_project")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tutoreligibilityrequestproject",
            constraint=models.UniqueConstraint(
                fields=("request", "project"), name="uniq_elig_req_project"
            ),
        ),
        migrations.AddIndex(
            model_name="tutoreligibilityrequest",
            index=models.Index(fields=["status", "created_at"], name="elig_req_status_created"),
        ),
        migrations.AddConstraint(
            model_name="tutoreligibilityrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reviewed_at__isnull", True),
                        ("reviewed_by__isnull", True),
                        ("status", "pending"),
                    ),
                    models.Q(
                        models.Q(("status", "pending"), _negated=True),
                        ("reviewed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="elig_req_review_consistent",
            ),
        ),
    ]
